repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: ruff
        name: Ruff
        entry: ruff .
        language: system
        types: [python]
    -   id: mypy
        name: MyPy
        entry: mypy --strict --cache-dir=/dev/null .
        language: system
        types: [python]
    -   id: pytest
        name: Pytest
        entry: pytest
        language: system
        types: [python]
    -   id: isort
        name: Isort
        entry: isort .
        language: system
        types: [python]
