"""empty message

Revision ID: 1ea0834e4742
Revises: a803971795ba
Create Date: 2023-06-18 16:57:10.138946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1ea0834e4742"
down_revision = "a803971795ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "parsing_status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "UPDATE_REQUIRED", name="parsingstatusenum"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "match_hero",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column(
            "position",
            sa.Enum(
                "SAFE_LANE_CARRY",
                "SAFE_LANE_SUPPORT",
                "MID_LANE",
                "OFF_LANE_CORE",
                "OFF_LANE_SUPPORT",
                name="positionenum",
            ),
            nullable=False,
        ),
        sa.Column("gold_m", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["hero_id"],
            ["hero.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("user", "nickname", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "pass_hash", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "pass_hash", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "nickname", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("match_hero")
    op.drop_table("match")
    op.drop_table("hero")
    # ### end Alembic commands ###
