"""empty message

Revision ID: df79bd0c8ad5
Revises: 1ea0834e4742
Create Date: 2023-06-20 20:54:27.548736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df79bd0c8ad5"
down_revision = "1ea0834e4742"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE factionenum AS ENUM ('RADIANT', 'DIRE');")
    op.add_column("match", sa.Column("winner_faction", sa.Enum("RADIANT", "DIRE", name="factionenum"), nullable=False))
    op.add_column("match_hero", sa.Column("faction", sa.Enum("RADIANT", "DIRE", name="factionenum"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_hero", "faction")
    op.drop_column("match", "winner_faction")
    op.execute("DROP TYPE IF EXISTS factionenum")
    # ### end Alembic commands ###
